### PR TITLE
add basic setuptools install, update docs

### PR DESCRIPTION
**Pull request by purarue**
add a basic setup.py so that this is installable with pip, updated the documentation to reflect installation instructions

first time using the `#begin_src` stuff to generate the docs (and org-mode in general I suppose) - think I was able to mostly figure it out.

of course org mode has solved this issue, then theres me [solving the same thing](https://github.com/seanbreckenridge/pmark) with regex for markdown

### CODE REVIEW

**Comment by purarue** [comment]
Would probably resolve https://github.com/karlicoss/arctee/issues/3?

**Comment by karlicoss** [comment]
Yep, thanks!

For org-mode: I guess what's nice about it is that in principle one doesn't have to run emacs and figure it out, just editing as plaintext -- at some cost of duplicating changes. But otherwise I'm happy to refresh myself too.

Yeah -- literate programming is a recurring problem :( And still no good solutions really ticking everyting...

Btw, for gitignores (which I forgot here), I'm usually using this alias

`function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}`

Then can type something like `gi python,emacs >.gitignore` and it covers pretty much everything

**Comment by purarue** [comment]
Oh, I was using emacs -- [had to fix some fylcheck error first](https://github.com/seanbreckenridge/dotfiles/commit/7b6baa3f2a327ccd8219b864fd18130271a976e2) that was stopping me from running the src for python code. just not used to org mode/how to configure stuff yet, rely on doom for most of its defaults for now

> Btw, for gitignores (which I forgot here), I'm usually using this alias

ah, yeah -- wasnt sure if you wanted a big gitignore... not that a bloated gitignore really affects anything

I do the same:

```sh
[ ~ ] $ cat "$(which gi)"
#!/bin/sh
# get gitignores for different languages
if [ ! "$(echo "$@" | tr -d "\n\r")" = "" ] && [ ! "$1" = "list" ]; then
        printf "tags*\n*.pdf\n"
fi
curl -sL "https://gitignore.io/api/$*"
printf "\n"
```

**Comment by karlicoss** [comment]
Ugh. Tried LSP a few times with emacs as well and it never worked well sadly, often bringing everything to crawl :( 
Also using Doom by the way, it makes a lot of sense as the base config.

**Pull request merged**
